#!/usr/bin/env python
# Copyright (C) 2026 Apollo AI Lab, Inc.
# Licensed under the GNU General Public License, version 2 (GPL-2.0)
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            interface.cc
            luabridge_surface.cc
            server.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_luabridge"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    # NDEBUG removes GLib/assert overhead; -O2 enables optimisation without
    # the full -ffast-math of -O3 (safe for audio code).  Applied only to
    # this surface so the wider project build mode is unaffected.
    obj.defines     += [ 'NDEBUG' ]
    obj.cxxflags     = [ '-O2' ]
    obj.includes     = ['.']
    obj.name         = 'libardour_luabridge'
    obj.target       = 'ardour_luabridge'
    obj.uselib       = 'GLIBMM XML WEBSOCKETS OPENSSL'
    obj.use          = 'liblua libardour libardour_cp libgtkmm2ext libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

    if bld.env['build_target'] == 'mingw':
        obj.defines += [ '_WIN32_WINNT=0x0601', 'WINVER=0x0601' ]
